name: Naukari Resume Update_QA

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List files (root)
        run: dir

      - name: List all folders recursively
        run: cmd dir /s

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
    
      - name: Run Headless Browser Test
        run: mvn clean
        
      - name: Build & Run
        run: mvn clean test
        working-directory: Naukari
